# Autofix

name: autofix.ci # ワークフローの名前は `autofix.ci` でなければならない

# ワークフローを実行する条件
on:
  # メインブランチにプッシュもしくはプルリクエストが作成されたとき
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  # Autofix
  autofix:
    name: Script
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Get cache directory
        id: npm-cache-directory
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache
        id: npm-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-directory.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint:script:fix

      - name: Run Stylelint
        run: npm run lint:style:fix

      - name: Run Prettier
        run: npm run format

      - name: Autofix
        uses: autofix-ci/action@8bc06253bec489732e5f9c52884c7cace15c0160
